spring:
  application:
    name: service-gateway
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
      - id: SERVICE-HI                     #网关路由到eureka
        uri: lb://SERVICE-HI               # http也可以   LoadBalancerClient过滤器
        predicates:
          - Path=/SERVICE-HI/**            #路径   websocket长连接可以在lb后使用ws  lb: ws://serviceid
          - Weight=provide, 90             # 权重 可以不加
        filter:
          - RedirectTo=404, http://zhihu.com
#      - id: baidu
#        uri: http://baidu.com              # lb 不可以
#        method: GET                        # 请求方法
#        predicates:
#           - Path=/*
#        filter:
#        - RedirectTo=302, http://zhihu.com


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true
server:
  port: 8801


